spring.application.name=Real_Estate_Management

spring.datasource.url=jdbc:mysql://localhost:3306/reaL_estate_managment
spring.datasource.username=root
spring.datasource.password=Ankit@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_SsFEOkm1JdmgGK
razorpay.key.secret=VX61Vk2VWsDb5i5vPsjwcgBu